from gym_cellular_automata.forest_fire.operators.ca_DrosselSchwabl import ForestFire
from gym_cellular_automata.forest_fire.operators.ca_windy import WindyForestFire
from gym_cellular_automata.forest_fire.operators.modify import Modify
from gym_cellular_automata.forest_fire.operators.move import Move
from gym_cellular_automata.forest_fire.operators.repeat_ca import RepeatCA
